# Milvus配置
milvus:
  uri: http://134.175.83.172
  collection:
    name: beanmeat_test
    description: Beanmeat向量数据集合
    consistency-level: STRONG
    fields:
      id:
        data-type: Int64
        is-primary-key: true
        max-length: 64
      description:
        data-type: VarChar
        max-length: 1024
      segment:
        data-type: Int64
        max-length: 64
      description_vector:
        data-type: FloatVector
        dimension: 1024
        index-type: FLAT
        metric-type: COSINE

# 应用配置
server:
  port: 8080
  servlet:
    context-path: /api

# Swagger配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

# 日志配置
logging:
  level:
    com.beanmeat: DEBUG
    io.milvus: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
