# Milvus配置
milvus:
  host: localhost
  port: 19530
  database: default
  collection:
    name: beanmeat_vectors
    description: Beanmeat向量数据集合
    dimension: 1024
    metric-type: COSINE

# 应用配置
server:
  port: 8080
  servlet:
    context-path: /api

# Swagger配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

# 日志配置
logging:
  level:
    com.beanmeat: DEBUG
    io.milvus: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
